#!/bin/bash

release='dev'
if [ "$1" == 'release' ]; then
  release=''
fi

export TZ=UTC
year=$(date +%Y)
month=$(date +%m)
day=$(date +%d)
current_time=$(date +"%H%M%S")
version="$year.$month$day.$release$current_time"

REPO_ROOT=$(git rev-parse --show-toplevel)
version_file=$REPO_ROOT/ikabot/__init__.py

expression="s/__version__ = .*$/__version__ = '$version'/"

echo $version

case "$(uname -s)" in
    Darwin*)        sed -i '' "$expression" "$version_file" ;;
    Linux* | *)     sed -i "$expression" "$version_file" ;;
esac

git add $version_file
