#!/bin/bash

branch_name=$(git rev-parse --abbrev-ref HEAD)
release='dev'
if [ "$current_branch" == "main" ] || [ "$current_branch" == "master" ]; then
    echo Remove the branch name if main/master
    release=''
fi

year=$(date +%Y)
month=$(date +%m)
day=$(date +%d)
current_time=$(date +"%H%M%S")
version="$year.$month$day.$release$current_time"

REPO_ROOT=$(git rev-parse --show-toplevel)
setup_file=$REPO_ROOT/setup.py

expression="s/version=.*$/version='$version',/"

echo Version $version
echo Path    $setup_file

case "$(uname -s)" in
    Darwin*)        sed -i '' $expression $setup_file ;;
    Linux* | *)     sed -i $expression $setup_file ;;
esac

git add $setup_file
