#!/bin/bash

REPO_ROOT=$(git rev-parse --show-toplevel)

# Extract the year, month, and day from the tag
year=$(date +%Y)
month=$(date +%m)
day=$(date +%d)
branch_name=$(git rev-parse --abbrev-ref HEAD)
current_time=$(date +"%H%M%S")

version="$year.$month$day.$branch_name$current_time"
setup_file=$REPO_ROOT/setup.py

expression="s/version=.*$/version='$version',/"

echo Version $version
echo Path    $setup_file

case "$(uname -s)" in
    Darwin*)        sed -i '' $expression $setup_file ;;
    Linux* | *)     sed -i $expression $setup_file ;;
esac

git add $setup_file

