name: Set Version on Main/Master

on:
  push:
    branches:
      - main
      - master

jobs:
  set-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set Version
        run: |
          version=$(.githooks/pre-commit)
          git commit -m "Set release version to $version"
          git push
